FROM arm32v6/alpine:3.11
LABEL Maintainer="Merlin Beutlberger <r@ndombyte.net>" \
      Description="Lightweight Mosquitto MQTT server based on Alpine Linux. Fork of https://github.com/TrafeX/docker-alpine-mosquitto with added ARM support"

# Install packages
RUN apk --no-cache add mosquitto mosquitto-clients

# Expose MQTT port
EXPOSE 1883

ENV PATH /usr/sbin:$PATH

ENTRYPOINT ["/usr/sbin/mosquitto"]
